version: '3'
services:

        notebook:
                build:
                        context: ./docker
                        dockerfile: Dockerfile
                container_name: 'notebook_compvis'
                environment:
                        - JUPYTER_ENABLE_LAB=yes
                volumes:
                        - ./:/home/jovyan/work
                ports:
                        - '8888:8888'
